version: "3"
services:
  mongodb:
    image: mongo:3.6.22
    container_name: "mongodb"
    ports:
      - 27017:27017
    command: --smallfiles

  dataload:
    build: ./dataload
    links:
      - mongodb
    depends_on:
      - mongodb

  solar-system-service:
    build: .
    ports:
      - "3001:3001"
    depends_on:
      - mongodb
      - dataload
    links:
      - mongodb